import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Andrew',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Nan',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Sweater',
      category: 'Sweater',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Sweater',
      category: 'Sweater',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
	{
	  name: 'Floral Sweater',
      category: 'Sweater',
      image: '/images/p7.jpg',
      price: 64,
      countInStock: 15,
      brand: 'unk',
      rating: 5,
      numReviews: 0,
      description: 'sweater with floral pattern',
	},
	{
		name: 'Bath Robe',
      category: 'Essentials',
      image: '/images/p8.jpg',
      price: 32,
      countInStock: 16,
      brand: 'unk',
      rating: 5,
      numReviews: 0,
      description: 'bath robe for relaxation',
	},
	{
		name: 'Thin Sweatpants',
      category: 'Pants',
      image: '/images/p9.jpg',
      price: 32,
      countInStock: 11,
      brand: 'unk',
      rating: 4,
      numReviews: 0,
      description: 'thin cool sweatpants',
	},
	{
		name: 'Thin Sweater',
      category: 'Sweater',
      image: '/images/p10.jpg',
      price: 32,
      countInStock: 11,
      brand: 'unk',
      rating: 4,
      numReviews: 0,
      description: 'thin cool sweater',
	},
	{
		name: 'Slim Jeans',
      category: 'Pants',
      image: '/images/p11.jpg',
      price: 42,
      countInStock: 31,
      brand: 'unk',
      rating: 3.5,
      numReviews: 0,
      description: 'thin skinny jeans',
	},
	{
		name: 'Bubble Jacket',
      category: 'Jacket',
      image: '/images/p12.jpg',
      price: 124,
      countInStock: 31,
      brand: 'unk',
      rating: 4.5,
      numReviews: 0,
      description: 'warm bubble jacket',
	},
	{
		name: 'Dark Jeans',
      category: 'Pants',
      image: '/images/p13.jpg',
      price: 124,
      countInStock: 31,
      brand: 'unk',
      rating: 4.5,
      numReviews: 0,
      description: 'warm dark jeans',
	},
	{
		name: 'Green Dress',
      category: 'Dress',
      image: '/images/p14.jpg',
      price: 74,
      countInStock: 9,
      brand: 'unk',
      rating: 2.75,
      numReviews: 0,
      description: 'classy green dress',
	},
  ],
};
export default data;
